<a href="https://colab.research.google.com/github/rohanpashikanti/Data_Analytics/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# libraries Required

In [ ]:

import pandas as pd #--> which is used to import dataset.
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
ab = pd.read_csv('Automobile.csv')
# ab = pd.read_csv('CAvideos.csv',header= None) --> Used to importing csv without header.

# Printing the dataframe in Python
df prints the entire dataframe (not recommended for large datasets)

df.head(n) to show the first n rows of data frame.

df.tail(n) shows the bottom n rows of data frame

In [ ]:
ab.tail()

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
393,ford mustang gl,27.0,4,140.0,86.0,2790,15.6,82,usa
394,vw pickup,44.0,4,97.0,52.0,2130,24.6,82,europe
395,dodge rampage,32.0,4,135.0,84.0,2295,11.6,82,usa
396,ford ranger,28.0,4,120.0,79.0,2625,18.6,82,usa
397,chevy s-10,31.0,4,119.0,82.0,2720,19.4,82,usa

In [ ]:
ab.head(2)

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa

In [ ]:
ab.columns

Index(['name', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin'],
      dtype='object')

# Basic insights from the data

## Checking Data types

In [ ]:
ab.dtypes

name             object
mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

## Describing Data
for statistical data

In [ ]:
ab.describe(include='all')

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
count,398,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398
unique,305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,ford pinto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa
freq,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249
mean,NaN,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN
std,NaN,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN
min,NaN,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN
25%,NaN,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN
50%,NaN,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN
75%,NaN,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN
max,NaN,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,NaN

In [ ]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          398 non-null    object
 1   mpg           398 non-null    float64
 2   cylinders     398 non-null    int64
 3   displacement  398 non-null    float64
 4   horsepower    392 non-null    float64
 5   weight        398 non-null    int64
 6   acceleration  398 non-null    float64
 7   model_year    398 non-null    int64
 8   origin        398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

# Data pre-processing
The process of converting or mapping data from the initial "raw" form into another format, in order to prepare the data for further analysis.

## Dealing with Missing Values in Python

### drop missing values
axis=0 drops the entire row

axis=1 drops the entire column

In [ ]:
ab.count()

name            398
mpg             398
cylinders       398
displacement    398
horsepower      392
weight          398
acceleration    398
model_year      398
origin          398
dtype: int64

In [ ]:
# ab.dropna(subset=['horsepower'],axis=0,inplace=True)

### Replace missing data with frequency

In [ ]:
#MostFrequentEntry = df['attribute_name'].value_counts().idxmax()
#df['attribute_name'].replace(np.nan,MostFrequentEntry
#df['attribute_name'].replace(np.nan,MostFrequentEntry, inplace=True)

### Replace missing data with mean

In [ ]:
AverageValue=ab['horsepower'].mean(axis=0)
ab['horsepower'].replace(np.nan, AverageValue, inplace=True)

In [ ]:
ab.count()

name            398
mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
model_year      398
origin          398
dtype: int64

# Data Formatting